{% set name = "autobahn" %}
{% set version = "25.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01c4632b48f4fb2296ecd44eada9e584f76e9cab1f6d6f158393e7937c8a0e58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wamp = autobahn.__main__:_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - txaio >=21.2.1
    - cryptography >=3.4.6
    - hyperlink >=21.0.0
    - setuptools

test:
  imports:
    - autobahn
    - autobahn.rawsocket
    - autobahn.wamp
    - autobahn.websocket
    - autobahn.util
  requires:
    - pip
    - python {{ python_min }}
    # For cli autobahn[twisted]
    - zope.interface >=5.2.0
    - twisted >=24.3.0
    - attrs >=20.3.0
  commands:
    - pip check
    - wamp -h

about:
  home: https://github.com/crossbario/autobahn-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket and WAMP in Python for Twisted and asyncio

  doc_url: https://autobahn-python.readthedocs.io
  dev_url: https://github.com/crossbario/autobahn-python

extra:
  recipe-maintainers:
    - synapticarbors
