{% set name = "autobahn" %}
{% set version = "18.8.2" %}
{% set sha256 = "448df2e241011ea2948799918930042d81e63d26b01912c472f5a9a37f42f319" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  host:
    - python
    - pip
  run:
    - python
    - txaio >=18.7.1
    - six >=1.10.0

test:
  imports:
    - autobahn
    - autobahn.rawsocket
    - autobahn.wamp
    - autobahn.websocket
    - autobahn.util

about:
  home: https://github.com/crossbario/autobahn-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'WebSocket and WAMP in Python for Twisted and asyncio'

  doc_url: https://autobahn-python.readthedocs.io
  dev_url: https://github.com/crossbario/autobahn-python

extra:
  recipe-maintainers:
    - synapticarbors
