{% set name = "autobahn" %}
{% set version = "24.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2d71ef1b0cf780b6d11f8b205fd2c7749765e65795f2ea7d823796642ee92c9

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
  - wamp = autobahn.__main__:_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - txaio >=21.2.1
    - cryptography >=3.4.6
    - hyperlink >=21.0.0
    - setuptools

test:
  imports:
    - autobahn
    - autobahn.rawsocket
    - autobahn.wamp
    - autobahn.websocket
    - autobahn.util
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - wamp -h

about:
  home: https://github.com/crossbario/autobahn-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket and WAMP in Python for Twisted and asyncio

  doc_url: https://autobahn-python.readthedocs.io
  dev_url: https://github.com/crossbario/autobahn-python

extra:
  recipe-maintainers:
    - synapticarbors
