schema_version: 1

context:
  name: autobahn
  version: 25.9.1
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 01c4632b48f4fb2296ecd44eada9e584f76e9cab1f6d6f158393e7937c8a0e58

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - wamp = autobahn.__main__:_main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64
  run:
    - python >=${{ python_min }}
    - txaio >=25.9.2
    - cryptography >=3.4.6
    - hyperlink >=21.0.0

tests:
  - python:
      imports:
        - autobahn
        - autobahn.rawsocket
        - autobahn.wamp
        - autobahn.websocket
        - autobahn.util
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - zope.interface >=5.2.0
        - twisted >=24.3.0
        - attrs >=20.3.0
    script:
      - wamp -h

about:
  license: MIT
  license_file: LICENSE
  summary: WebSocket and WAMP in Python for Twisted and asyncio
  homepage: https://github.com/crossbario/autobahn-python
  repository: https://github.com/crossbario/autobahn-python
  documentation: https://autobahn-python.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
